// <auto-generated />
using GreekShooping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GreekShooping.ProductAPI.Migrations.PostgreSQL
{
    [DbContext(typeof(PostgreSQLContext))]
    partial class PostgreSQLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GreekShooping.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            CategoryName = "T-shirt",
                            Description = "O Lorem Ipsum tem vindo a ser o texto padrão usado por estas indústrias desde o ano de 1500",
                            ImageURL = "https://61971.cdn.lojaquevende.com.br/static/61971/sku/roupas-camisetas-femininas-produto-teste-camiseta-mulher-maravilha-vermelha-pode-excluir-1494093213682.jpg",
                            Name = "Camisa",
                            Price = 29.9m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "T-shirt",
                            Description = "O Lorem Ipsum tem vindo a ser o texto padrão usado por estas indústrias desde o ano de 1500",
                            ImageURL = "https://61971.cdn.lojaquevende.com.br/static/61971/sku/roupas-camisetas-masculinas-produto-teste-camiseta-batman-preta-pode-excluir-1494097276451.jpg",
                            Name = "Camisa Batiman",
                            Price = 39.9m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "T-shirt",
                            Description = "O Lorem Ipsum tem vindo a ser o texto padrão usado por estas indústrias desde o ano de 1500",
                            ImageURL = "https://www.dhresource.com/0x0/f2/albu/g19/M01/96/0D/rBVap2D4WzqAKVR5AABxIIhKL0E891.jpg/men-s-t-shirts-summer-fashion-game-doom-t.jpg",
                            Name = "Camisa Doom",
                            Price = 49.9m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "T-shirt",
                            Description = "O Lorem Ipsum tem vindo a ser o texto padrão usado por estas indústrias desde o ano de 1500",
                            ImageURL = "https://cf.shopee.com.br/file/c1637a3157672c360efaee48680ecca9",
                            Name = "Camiseta",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "T-shirt",
                            Description = "O Lorem Ipsum tem vindo a ser o texto padrão usado por estas indústrias desde o ano de 1500",
                            ImageURL = "https://bawclothing.vtexassets.com/arquivos/ids/162432/BAW_1539.jpg?v=636662291912030000",
                            Name = "Camisa",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "T-shirt",
                            Description = "O Lorem Ipsum tem vindo a ser o texto padrão usado por estas indústrias desde o ano de 1500",
                            ImageURL = "https://m.media-amazon.com/images/I/51s4mGEZGlL._AC_SX385_.jpg",
                            Name = "Camisa manga longa",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryName = "T-shirt",
                            Description = "O Lorem Ipsum tem vindo a ser o texto padrão usado por estas indústrias desde o ano de 1500",
                            ImageURL = "https://images.lojanike.com.br/1024x1024/produto/camisa-nike-franca-i-202021-torcedor-pro-masculina-CD0700-498-1.jpg",
                            Name = "Camisa nike",
                            Price = 89.9m
                        },
                        new
                        {
                            Id = 9L,
                            CategoryName = "T-shirt",
                            Description = "O Lorem Ipsum tem vindo a ser o texto padrão usado por estas indústrias desde o ano de 1500",
                            ImageURL = "https://static.netshoes.com.br/produtos/camisa-cruzeiro-i-2122-sn-torcedor-adidas-masculina/08/NQQ-7747-008/NQQ-7747-008_zoom1.jpg?ts=1615489262&ims=544x",
                            Name = "Camisa azul",
                            Price = 99.9m
                        },
                        new
                        {
                            Id = 10L,
                            CategoryName = "T-shirt",
                            Description = "O Lorem Ipsum tem vindo a ser o texto padrão usado por estas indústrias desde o ano de 1500",
                            ImageURL = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbugaKdtuKaiT57tnUbRydFQnV_t0rbu7inA&usqp=CAU",
                            Name = "Camisa Atletico MG",
                            Price = 109.9m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
